/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Faculty;

import com.oracle.jrockit.jfr.ContentType;
import java.awt.Graphics;
import java.awt.Image;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Sahib
 */
public class Faculty extends javax.swing.JFrame {

    /**
     * Creates new form Faculty
     */
    Socket sock;
    FileInputStream fis;
    FileOutputStream fos;
    DataInputStream dis;
    DataOutputStream dos;
    FacultyClass fac;
    Image im;
    FacultyHomepage ob;
    ChangePassword ob1;
    EditProfile ob2;
    EditPhoto ob3;
    AddNotes ob4;
    ArrayList<StudentData> al;
    Long size;
    String s1 = "";

    public Faculty() {
        initComponents();
        setSize(400, 200);
        registerpan.setVisible(false);
        loginpan.setVisible(false);
        facultypan.setVisible(false);
        fac = new FacultyClass();
        try {
            sock = new Socket("127.0.0.1", 65000);
            System.out.println("Success");
            dis = new DataInputStream(sock.getInputStream());
            dos = new DataOutputStream(sock.getOutputStream());
            String s = dis.readLine();
            if (s.equals("Hello")) {
                Thread t = new Thread(new Receiver());
                t.start();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Connection could not be established");
            System.exit(0);
        }
        File f = new File("C:\\pics1");
        if (f.exists()) {
        } else {
            f.mkdir();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        facultypan = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        registerpan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordtf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        confirmtf = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        coursecb = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        departmentcb = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        loginpan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        facultytf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        password1tf = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel1.setText("FACULTY");

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("Password");

        jLabel4.setText("Confirm Password");

        jLabel5.setText("Course");

        coursecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Course" }));

        jLabel6.setText("Department");

        departmentcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Department" }));
        departmentcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentcbActionPerformed(evt);
            }
        });

        jButton3.setText("REGISTER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerpanLayout = new javax.swing.GroupLayout(registerpan);
        registerpan.setLayout(registerpanLayout);
        registerpanLayout.setHorizontalGroup(
            registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coursecb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(departmentcb, 0, 197, Short.MAX_VALUE)
                    .addComponent(confirmtf)
                    .addComponent(nametf)
                    .addComponent(passwordtf))
                .addContainerGap())
            .addGroup(registerpanLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerpanLayout.setVerticalGroup(
            registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(confirmtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(departmentcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(coursecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel7.setText("Faculty Id");

        jLabel8.setText("Password");

        jButton4.setText("LOGIN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginpanLayout = new javax.swing.GroupLayout(loginpan);
        loginpan.setLayout(loginpanLayout);
        loginpanLayout.setHorizontalGroup(
            loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password1tf, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(facultytf))
                .addContainerGap())
            .addGroup(loginpanLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginpanLayout.setVerticalGroup(
            loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(facultytf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(password1tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout facultypanLayout = new javax.swing.GroupLayout(facultypan);
        facultypan.setLayout(facultypanLayout);
        facultypanLayout.setHorizontalGroup(
            facultypanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facultypanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultypanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerpan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, facultypanLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        facultypanLayout.setVerticalGroup(
            facultypanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultypanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultypanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(30, 30, 30)
                .addComponent(registerpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(facultypan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(facultypan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        registerpan.setVisible(true);
        loginpan.setVisible(false);
        setSize(400, 420);
        try {
            dos.writeBytes("Request Department\r\n");
            dos.writeBytes("Homepage Data\r\n");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Could not fetch Sufficient Data");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void departmentcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentcbActionPerformed
        try {
            if (departmentcb.getSelectedIndex() != 0) {
                dos.writeBytes("Request Course\r\n");
                dos.writeBytes(departmentcb.getSelectedItem() + "\r\n");
                dos.writeBytes("Homepage\r\n");
            } else {
                coursecb.removeAllItems();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_departmentcbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (nametf.getText().equals("") || passwordtf.getText().equals("") || confirmtf.getText().equals("") || departmentcb.getSelectedIndex() == 0 || coursecb.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "All Fields are mandatory");
        } else {
            if (passwordtf.getText().equals(confirmtf.getText())) {
                try {
                    System.out.println("hello1");
                    dos.writeBytes("Register Faculty Request\r\n");
                    System.out.println("hello2");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Unable to send register request");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Passwords do not match");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        loginpan.setVisible(true);
        registerpan.setVisible(false);
        setSize(400, 310);
        loginpan.setBounds(100, 10, 390, 200);
        facultytf.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (facultytf.getText().equals("") || password1tf.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Both fields are mandatory");
        } else {
            try {
                fac.id = Integer.parseInt(facultytf.getText());
                try {
                    dos.writeBytes("Faculty Login Request\r\n");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Connection with server failed");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Faculty id must be integer");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    class Receiver implements Runnable {

        @Override
        public void run() {
            facultypan.setVisible(true);
            try {
                while (true) {
                    String s = dis.readLine();
                    System.out.println(s);
                    if (s.equals("Department March")) {
                        String s5 = dis.readLine();
                        if (s5.equals("Homepage Data")) {
                            departmentcb.removeAllItems();
                            departmentcb.addItem("Select Department");
                            while (true) {
                                String s1 = dis.readLine();
                                if (s1.equals("khatam")) {
                                    break;
                                } else {
                                    departmentcb.addItem(s1);
                                }
                            }
                        } else if (s5.equals("AddNotes Data")) {
                            ob4.cbDepartment.removeAllItems();
                            ob4.cbDepartment.addItem("Select Department");
                            while (true) {
                                String s6 = dis.readLine();
                                if (s6.equals("khatam")) {
                                    break;
                                } else {
                                    ob4.cbDepartment.addItem(s6);
                                }
                            }
                        }
                    } else if (s.equals("Course March")) {
                        String s2 = dis.readLine();
                        if (s2.equals("Homepage")) {
                            coursecb.removeAllItems();
                            coursecb.addItem("Select Course");
                            while (true) {
                                String s1 = dis.readLine();
                                if (s1.equals("khatam")) {
                                    break;
                                } else {
                                    coursecb.addItem(s1);
                                }
                                System.out.println(s1);
                            }
                            System.out.println("heelo");
                        } else if (s2.equals("AddNotes")) {
                            ob4.cbCourse.removeAllItems();
                            ob4.cbCourse.addItem("Select Course");
                            while (true) {
                                String s1 = dis.readLine();
                                if (s1.equals("khatam")) {
                                    break;
                                } else {
                                    ob4.cbCourse.addItem(s1);
                                }
                            }
                        }
                        System.out.println("heelo231223");
                    } else if (s.equals("Register Faculty Request Accepted")) {
                        System.out.println("do");
                        dos.writeBytes(nametf.getText() + "\r\n");
                        dos.writeBytes(passwordtf.getText() + "\r\n");
                        dos.writeBytes(departmentcb.getSelectedItem().toString() + "\r\n");
                        dos.writeBytes(coursecb.getSelectedItem().toString() + "\r\n");
                        Date d = new Date();
                        System.out.println(d.getTime());
                        dos.writeLong(d.getTime());
                        String s1 = dis.readLine();
                        if (s1.equals("Registered Successfully")) {
                            int id = dis.readInt();
                            JOptionPane.showMessageDialog(null, "Registered Successfully\nYou can login using ID: " + id);
                            nametf.setText("");
                            passwordtf.setText("");
                            confirmtf.setText("");
                            coursecb.setSelectedIndex(0);
                            registerpan.setVisible(false);
                            setSize(400, 200);
                        }
                    } else if (s.equals("Faculty Login Request Accepted")) {
                        dos.writeInt(fac.id);
                        dos.writeBytes(password1tf.getText() + "\r\n");
                        String s1 = dis.readLine();
                        if (s1.equals("Login Successful")) {
                            dispose();
                            dos.writeBytes("Faculty Data Request\r\n");
                        } else {
                            JOptionPane.showMessageDialog(null, "Invalid FacultyID or Password");
                        }
                    } else if (s.equals("Faculty Data Request Accepted")) {
                        dos.writeInt(fac.id);
                        fac.username = dis.readLine();
                        fac.department = dis.readLine();
                        fac.course = dis.readLine();
                        fac.email = dis.readLine();
                        fac.contact = dis.readLine();
                        fac.address = dis.readLine();
                        fac.qualification = dis.readLine();
                        long count = 0, size = dis.readLong();
                        fos = new FileOutputStream("C:\\pics1\\" + fac.id + ".jpg");
                        System.out.println(size);
                        byte[] b = new byte[100000];
                        int r;
                        while (count != size) {
                            r = dis.read(b, 0, 100000);
                            count += r;
                            fos.write(b, 0, r);
                        }
                        im = ImageIO.read(new File("C:\\pics1\\" + fac.id + ".jpg"));

                        ob = new FacultyHomepage();
                        ob.repaint();
                        fos.close();
                        ob.setVisible(true);
                    } else if (s.equals("Faculty Change Password Request Accepted")) {
                        try {
                            dos.writeInt(fac.id);
                            dos.writeBytes(ob1.currentpasstf.getText() + "\r\n");
                            dos.writeBytes(ob1.newpasstf.getText() + "\r\n");
                            String s2 = dis.readLine();
                            if (s2.equals("Password Change Successful")) {
                                JOptionPane.showMessageDialog(ob1, "Password Change Successful");
                                ob1.dispose();
                            } else if (s2.equals("Invalid Current Password")) {
                                JOptionPane.showMessageDialog(ob1, "Invalid Current Password");
                            }
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    } else if (s.equals("Faculty Edit Profile Request Accepted")) {
                        try {
                            dos.writeInt(fac.id);
                            dos.writeBytes(ob2.emailtf.getText() + "\r\n");
                            dos.writeBytes(ob2.contacttf.getText() + "\r\n");
                            dos.writeBytes(ob2.addressta.getText() + "\r\n");
                            dos.writeBytes(ob2.qualificationta.getText() + "\r\n");
                            String s1 = dis.readLine();
                            if (s1.equals("Profile Updated Successfully")) {
                                JOptionPane.showMessageDialog(ob2, s1);
                                ob2.dispose();
                                ob.dispose();
                                dos.writeBytes("Faculty Data Request\r\n");
                            } else {
                                JOptionPane.showMessageDialog(ob2, "Profile Update Failed");;
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Connection Lost");
                        }
                    } else if (s.equals("Edit Photo Accepted")) {
                        dos.writeBytes("Faculty\r\n");
                        dos.writeInt(fac.id);
                        dos.writeLong(size);
                        fis = new FileInputStream(new File(s1));
                        byte[] b = new byte[100000];
                        int r;
                        while (true) {
                            r = fis.read(b, 0, 100000);
                            if (r == -1) {
                                break;
                            }
                            dos.write(b, 0, r);
                        }
                        String s1 = dis.readLine();
                        if (s1.equals("File Uploaded Successfully")) {
                            JOptionPane.showMessageDialog(ob3, s1);
                            ob3.dispose();
                            dos.writeBytes("Faculty Data Request\r\n");
                            dos.writeInt(fac.id);

                        }
                    } else if (s.equals("Request Student Data Accepted")) {
                        dos.writeBytes(ob4.cbDepartment.getSelectedItem().toString() + "\r\n");
                        dos.writeBytes(ob4.cbCourse.getSelectedItem().toString() + "\r\n");
                        while (true) {
                            String rollno = dis.readLine();
                            if (!rollno.equals("khatam")) {
                                String name = dis.readLine();
                                String email = dis.readLine();
                                String contact = dis.readLine();
                                al.add(new StudentData(new Boolean(true), rollno, name, email, contact));
                            } else {
                                break;
                            }
                        }
                        ob4.tm.fireTableDataChanged();
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public class FacultyHomepage extends javax.swing.JFrame {

        /**
         * Creates new form FacultyHomepage
         */
        public FacultyHomepage() {
            initComponents();
            namelb.setText(fac.username);
            departmentlb.setText(fac.department);
            courselb.setText(fac.course);
            if (!fac.email.equals("")) {
                emaillb.setText(fac.email);
            } else {
                emaillb.setText("      --");
            }
            if (!fac.contact.equals("")) {
                contactlb.setText(fac.contact);
            } else {
                contactlb.setText("      --");
            }
            if (!fac.address.equals("")) {
                addresslb.setText(fac.address);
            } else {
                addresslb.setText("      --");
            }
            if (!fac.qualification.equals("")) {
                qualificationlb.setText(fac.qualification);
            } else {
                qualificationlb.setText("      --");
            }
            setVisible(true);
        }

        @Override
        public void paint(Graphics g) {
            super.paint(g);
            g.drawImage(im, 20, 70, 70, 80, null);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jPanel1 = new javax.swing.JPanel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();
            qualificationlb = new javax.swing.JLabel();
            addresslb = new javax.swing.JLabel();
            contactlb = new javax.swing.JLabel();
            emaillb = new javax.swing.JLabel();
            courselb = new javax.swing.JLabel();
            departmentlb = new javax.swing.JLabel();
            namelb = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();
            jButton3 = new javax.swing.JButton();
            jButton4 = new javax.swing.JButton();
            jButton5 = new javax.swing.JButton();
            jButton6 = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
            jLabel1.setText("FACULTY HOMEPAGE");

            jLabel2.setText("Photo Here");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addContainerGap(75, Short.MAX_VALUE))
            );

            jLabel3.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel3.setText("Name");

            jLabel4.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel4.setText("Department");

            jLabel5.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel5.setText("Course");

            jLabel6.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel6.setText("Email");

            jLabel7.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel7.setText("Contact");

            jLabel8.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel8.setText("Address");

            jLabel9.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel9.setText("Qualification");

            qualificationlb.setText("jLabel10");

            addresslb.setText("jLabel11");

            contactlb.setText("jLabel12");

            emaillb.setText("jLabel13");

            courselb.setText("jLabel14");

            departmentlb.setText("jLabel15");

            namelb.setText("jLabel16");

            jButton1.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton1.setText("Change Password");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton2.setText("Edit Profile");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jButton3.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton3.setText("Edit Profile Pic");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });

            jButton4.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton4.setText("View History");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });

            jButton5.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton5.setText("Add Notes");
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
                }
            });

            jButton6.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton6.setText("Sign Out");
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel3))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(namelb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                                                            .addComponent(jButton1))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(departmentlb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(courselb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(emaillb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(contactlb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(qualificationlb)
                                                            .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(addresslb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(158, 158, 158)
                                            .addComponent(jLabel1)))
                            .addContainerGap())
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel3)
                                                    .addComponent(namelb)
                                                    .addComponent(jButton1))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel4)
                                                    .addComponent(departmentlb)
                                                    .addComponent(jButton2))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel5)
                                                    .addComponent(courselb)
                                                    .addComponent(jButton3))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel6)
                                                    .addComponent(emaillb)
                                                    .addComponent(jButton4))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(contactlb)
                                    .addComponent(jButton5))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(addresslb)
                                    .addComponent(jButton6))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(qualificationlb))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>                        

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            ob1 = new Faculty.ChangePassword();
            ob1.setVisible(true);
        }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
            ob2 = new Faculty.EditProfile();
            ob2.setVisible(true);
        }

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
            ob3 = new EditPhoto();
            ob3.setVisible(true);
        }

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {

        }

        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
            ob4 = new AddNotes();
            ob4.setVisible(true);
        }

        private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
            ob.dispose();
            new Faculty().setVisible(true);
        }

        /**
         * @param args the command line arguments
         */
        // Variables declaration - do not modify                     
        private javax.swing.JLabel addresslb;
        private javax.swing.JLabel contactlb;
        private javax.swing.JLabel courselb;
        private javax.swing.JLabel departmentlb;
        private javax.swing.JLabel emaillb;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JButton jButton6;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel namelb;
        private javax.swing.JLabel qualificationlb;
        // End of variables declaration                   
    }

    public class ChangePassword extends javax.swing.JFrame {

        /**
         * Creates new form ChangePassword
         */
        public ChangePassword() {
            initComponents();
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            currentpasstf = new javax.swing.JPasswordField();
            jLabel3 = new javax.swing.JLabel();
            newpasstf = new javax.swing.JPasswordField();
            jLabel4 = new javax.swing.JLabel();
            confirmpasstf = new javax.swing.JPasswordField();
            jButton1 = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
            jLabel1.setText("CHANGE PASSWORD");

            jLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jLabel2.setText("Current Password");

            jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jLabel3.setText("New Password");

            jLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jLabel4.setText("Confirm Password");

            jButton1.setFont(new java.awt.Font("Tekton Pro", 0, 16)); // NOI18N
            jButton1.setText("OK");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(newpasstf, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(currentpasstf, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(confirmpasstf, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel2)
                                            .addGap(0, 0, Short.MAX_VALUE)))
                            .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 58, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                            .addGap(124, 124, 124)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(currentpasstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(newpasstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(confirmpasstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                            .addComponent(jButton1)
                            .addContainerGap())
            );

            pack();
        }// </editor-fold>                        

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            if (currentpasstf.getText().equals("") || newpasstf.getText().equals("") || confirmpasstf.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "All Fields are Mandatory");
            } else {
                if (newpasstf.getText().equals(confirmpasstf.getText())) {
                    if (currentpasstf.getText().equals(newpasstf.getText())) {
                        JOptionPane.showMessageDialog(this, "New Password must be different from current password");
                    } else {
                        try {
                            dos.writeBytes("Faculty Change Password Request\r\n");
                        } catch (IOException ex) {
                            JOptionPane.showMessageDialog(this, "Connection Lost");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Confirm password does not match");
                }
            }
        }

        /**
         * @param args the command line arguments
         */
        // Variables declaration - do not modify                     
        private javax.swing.JPasswordField confirmpasstf;
        private javax.swing.JPasswordField currentpasstf;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPasswordField newpasstf;
        // End of variables declaration                   
    }

    public class EditProfile extends javax.swing.JFrame {

        /**
         * Creates new form EditProfile
         */
        public EditProfile() {
            initComponents();
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            if (!fac.email.equals("null")) {
                emailtf.setText(fac.email);
            }
            if (!fac.contact.equals("null")) {
                contacttf.setText(fac.contact);
            }
            if (!fac.address.equals("null")) {
                addressta.setText(fac.address);
            }
            if (!fac.qualification.equals("null")) {
                qualificationta.setText(fac.qualification);
            }
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            emailtf = new javax.swing.JTextField();
            contacttf = new javax.swing.JTextField();
            jScrollPane1 = new javax.swing.JScrollPane();
            addressta = new javax.swing.JTextArea();
            jScrollPane2 = new javax.swing.JScrollPane();
            qualificationta = new javax.swing.JTextArea();
            jButton1 = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
            jLabel1.setText("EDIT PROFILE");

            jLabel2.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel2.setText("Email");

            jLabel3.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel3.setText("Contact");

            jLabel4.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel4.setText("Address");

            jLabel5.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel5.setText("Qualification");

            addressta.setColumns(20);
            addressta.setRows(5);
            jScrollPane1.setViewportView(addressta);

            qualificationta.setColumns(20);
            qualificationta.setRows(5);
            jScrollPane2.setViewportView(qualificationta);

            jButton1.setText("Update");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(75, 75, 75)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(contacttf)
                                                    .addComponent(emailtf)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane2))))
                            .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(contacttf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addComponent(jButton1)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>                        

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            String email = emailtf.getText();
            String contact = contacttf.getText();
            String address = addressta.getText();
            String qual = qualificationta.getText();
            if (email.equals(fac.email) && contact.equals(fac.contact) && address.equals(fac.address) && qual.equals(fac.qualification)) {
                JOptionPane.showMessageDialog(this, "You must change atleast one field");
                //} else if (emailtf.getText().equals("") && contacttf.getText().equals("") && addressta.getText().equals("") && qualificationta.getText().equals("")) {
                // JOptionPane.showMessageDialog(this, "Atleast one field must be entered");
            } else {
                boolean flag = true, flag2 = true;
                if (contact.length() != 0) {
                    if (contact.length() >= 10 && contact.length() <= 12) {
                        try {
                            Long.parseLong(contact);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(this, "Contact can contain only digits");
                            flag = false;
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Contact can only contain 10-12 digits");
                        flag = false;
                    }
                }
                if (email.length() != 0) {
                    if (email.contains("@")) {
                        email = email.substring(email.indexOf('@'));
                        if (email.contains(".")) {
                        } else {
                            flag2 = false;
                            JOptionPane.showMessageDialog(this, "Email address not valid");
                        }
                    } else {
                        flag2 = false;
                        JOptionPane.showMessageDialog(this, "@ must be included in email");
                        emailtf.requestFocus();
                    }
                }
                if (flag && flag2) {
                    try {
                        dos.writeBytes("Faculty Edit Profile Request\r\n");
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, "Connection Lost");
                    }
                }
            }
        }

        /**
         * @param args the command line arguments
         */
        // Variables declaration - do not modify                     
        private javax.swing.JTextArea addressta;
        private javax.swing.JTextField contacttf;
        private javax.swing.JTextField emailtf;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextArea qualificationta;
        // End of variables declaration                   
    }

    public class EditPhoto extends javax.swing.JFrame {

        JFileChooser jfc;

        public EditPhoto() {
            initComponents();
            setSize(450, 300);
            jfc = new JFileChooser();
        }

        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            tfPath = new javax.swing.JTextField();
            jLabel2 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            getContentPane().setLayout(null);

            jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
            jLabel1.setText("Edit Photo");
            getContentPane().add(jLabel1);
            jLabel1.setBounds(140, 10, 110, 50);
            getContentPane().add(tfPath);
            tfPath.setBounds(90, 70, 190, 30);

            jLabel2.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel2.setText("Source");
            getContentPane().add(jLabel2);
            jLabel2.setBounds(10, 70, 60, 30);

            jButton1.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton1.setText("Browse");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton1);
            jButton1.setBounds(300, 70, 90, 30);

            jButton2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton2.setText("Upload");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton2);
            jButton2.setBounds(140, 133, 100, 30);

            pack();
        }// </editor-fold>                        

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            int i = jfc.showOpenDialog(this);
            if (i == JFileChooser.APPROVE_OPTION) {
                File f = jfc.getSelectedFile();
                s1 = f.getPath();
                tfPath.setText(s1);
                size = f.length();
            }
        }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
            if (s1.equals("")) {
                JOptionPane.showMessageDialog(this, "No Image Selected");
            } else {
                if (s1.endsWith(".jpg") || s1.endsWith(".jpeg") || s1.endsWith(".png") || s1.endsWith(".gif")) {
                    try {
                        dos.writeBytes("Profile Pic Coming\r\n");
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Filetype not compatible with predefined. Try .jpg format");
                }
            }
        }

        // Variables declaration - do not modify                     
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JTextField tfPath;
        // End of variables declaration                   
    }

    class StudentData {

        String rollno, name, email, contact;
        Boolean cb;

        StudentData(Boolean cb, String r, String n, String e, String c) {
            rollno = r;
            name = n;
            email = e;
            contact = c;
            this.cb = cb;
        }
    }

    public class AddNotes extends javax.swing.JFrame {

        JFileChooser jfc;
        TableModel tm;

        public AddNotes() {
            initComponents();
            setSize(500, 600);
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            al = new ArrayList<StudentData>();
            tm = new TableModel();
            jTable1.setModel(tm);
            try {
                dos.writeBytes("Request Department\r\n");
                dos.writeBytes("AddNotes Data\r\n");
                System.out.println("789");
            } catch (Exception e) {
                e.printStackTrace();
            }
            cbType.addItem("Audio");
            cbType.addItem("Video");
            cbType.addItem("Image");
            cbType.addItem("PDF");
        }

        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            cbDepartment = new javax.swing.JComboBox();
            cbCourse = new javax.swing.JComboBox();
            tfTitle = new javax.swing.JTextField();
            tfDescription = new javax.swing.JTextField();
            cbType = new javax.swing.JComboBox();
            btBrowse = new javax.swing.JButton();
            jScrollPane1 = new javax.swing.JScrollPane();
            jTable1 = new javax.swing.JTable();
            jLabel7 = new javax.swing.JLabel();
            btAdd = new javax.swing.JButton();
            lbPath = new javax.swing.JLabel();
            btHistory = new javax.swing.JButton();
            btSelect = new javax.swing.JButton();
            btDeselect = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            getContentPane().setLayout(null);

            jLabel1.setText("Department");
            getContentPane().add(jLabel1);
            jLabel1.setBounds(30, 80, 90, 20);

            jLabel2.setText("Course");
            getContentPane().add(jLabel2);
            jLabel2.setBounds(30, 110, 50, 20);

            jLabel3.setText("Title");
            getContentPane().add(jLabel3);
            jLabel3.setBounds(30, 150, 40, 20);

            jLabel4.setText("Description");
            getContentPane().add(jLabel4);
            jLabel4.setBounds(30, 190, 90, 20);

            jLabel5.setText("Type");
            getContentPane().add(jLabel5);
            jLabel5.setBounds(30, 230, 40, 20);

            jLabel6.setText("Select File");
            getContentPane().add(jLabel6);
            jLabel6.setBounds(30, 280, 80, 20);

            cbDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Select Department"}));
            getContentPane().add(cbDepartment);
            cbDepartment.setBounds(130, 70, 170, 30);
            cbDepartment.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cbDepartmentActionPerformed(evt);
                }
            });

            cbCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Select Course"}));
            cbCourse.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cbCourseActionPerformed(evt);
                }
            });
            getContentPane().add(cbCourse);
            cbCourse.setBounds(130, 100, 170, 30);
            getContentPane().add(tfTitle);
            tfTitle.setBounds(130, 140, 170, 30);
            getContentPane().add(tfDescription);
            tfDescription.setBounds(130, 180, 170, 30);

            cbType.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Select type"}));
            cbType.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    cbTypeItemStateChanged(evt);
                }
            });
            getContentPane().add(cbType);
            cbType.setBounds(130, 230, 120, 30);

            btBrowse.setText("Browse");
            btBrowse.setEnabled(false);
            btBrowse.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btBrowseActionPerformed(evt);
                }
            });
            getContentPane().add(btBrowse);
            btBrowse.setBounds(330, 283, 90, 30);

            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{
                        {},
                        {},
                        {},
                        {}
                    },
                    new String[]{}
            ));
            jScrollPane1.setViewportView(jTable1);

            getContentPane().add(jScrollPane1);
            jScrollPane1.setBounds(20, 330, 410, 120);

            jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel7.setText("Add Notes");
            getContentPane().add(jLabel7);
            jLabel7.setBounds(150, 10, 140, 30);

            btAdd.setText("Add");
            btAdd.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btAddActionPerformed(evt);
                }
            });
            getContentPane().add(btAdd);
            btAdd.setBounds(210, 540, 51, 23);
            getContentPane().add(lbPath);
            lbPath.setBounds(130, 280, 190, 30);

            btHistory.setText("View History");
            getContentPane().add(btHistory);
            btHistory.setBounds(293, 20, 120, 30);

            btSelect.setText("Select All");
            btSelect.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btSelectActionPerformed(evt);
                }
            });
            getContentPane().add(btSelect);
            btSelect.setBounds(60, 460, 90, 30);

            btDeselect.setText("Deselect All");
            btDeselect.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btDeselectActionPerformed(evt);
                }
            });
            getContentPane().add(btDeselect);
            btDeselect.setBounds(283, 460, 110, 30);

            pack();
        }// </editor-fold>                        

        private void btBrowseActionPerformed(java.awt.event.ActionEvent evt) {
            jfc = new JFileChooser("c:\\");
            int i = jfc.showOpenDialog(this);
            if (i == JFileChooser.APPROVE_OPTION) {
                File f = jfc.getSelectedFile();
                String path = f.getPath();
                if (cbType.getSelectedIndex() == 1) {
                    if (path.endsWith(".mp3") || path.endsWith(".wav") || path.endsWith(".wma") || path.endsWith(".ogg")) {
                        lbPath.setText(path);
                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid File Selected");
                    }
                } else if (cbType.getSelectedIndex() == 2) {
                    if (path.endsWith(".3gp") || path.endsWith(".mp4") || path.endsWith(".mpeg") || path.endsWith(".avi") || path.endsWith(".mkv")) {
                        lbPath.setText(path);
                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid File Selected");
                    }
                } else if (cbType.getSelectedIndex() == 3) {
                    if (path.endsWith(".jpeg") || path.endsWith(".jpg") || path.endsWith(".png") || path.endsWith(".gif")) {
                        lbPath.setText(path);
                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid File Selected");
                    }
                } else if (cbType.getSelectedIndex() == 4) {
                    if (path.endsWith(".pdf")) {
                        lbPath.setText(path);
                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid File Selected");
                    }
                }
            }
        }

        private void btAddActionPerformed(java.awt.event.ActionEvent evt) {

        }

        private void cbTypeItemStateChanged(java.awt.event.ItemEvent evt) {
            if (cbType.getSelectedIndex() == 0) {
                btBrowse.setEnabled(false);
            } else {
                btBrowse.setEnabled(true);
            }
        }

        private void cbDepartmentActionPerformed(java.awt.event.ActionEvent evt) {
            try {
                if (cbDepartment.getSelectedIndex() != 0) {
                    dos.writeBytes("Request Course\r\n");
                    dos.writeBytes(cbDepartment.getSelectedItem() + "\r\n");
                    dos.writeBytes("AddNotes\r\n");
                    System.out.println("456");
                } else {
                    cbCourse.removeAllItems();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        private void cbCourseActionPerformed(java.awt.event.ActionEvent evt) {
            System.out.println("123");
            try {
                //dos.writeBytes("Request Student Data\r\n");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Connection Lost");
            }
        }

        private void btSelectActionPerformed(java.awt.event.ActionEvent evt) {

        }

        private void btDeselectActionPerformed(java.awt.event.ActionEvent evt) {

        }

        class TableModel extends AbstractTableModel {

            @Override
            public int getRowCount() {
                return al.size();
            }

            @Override
            public int getColumnCount() {
                return 5;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                if (columnIndex == 0) {
                    return al.get(rowIndex).cb;
                } else if (columnIndex == 1) {
                    return al.get(rowIndex).rollno;
                } else if (columnIndex == 2) {
                    return al.get(rowIndex).name;
                } else if (columnIndex == 3) {
                    return al.get(rowIndex).email;
                } else if (columnIndex == 4) {
                    return al.get(rowIndex).contact;
                }
                return "";
            }

            @Override
            public String getColumnName(int column) {
                String s[] = {"Select Student", "Roll No", "Name", "Email", "Contact"};
                return s[column];
            }

            @Override
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }

            @Override
            public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
                al.get(rowIndex).cb = (Boolean) (aValue);
                fireTableCellUpdated(rowIndex, columnIndex);
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                if (columnIndex == 0) {
                    return true;
                } else {
                    return false;
                }
            }
        }

        // Variables declaration - do not modify                     
        private javax.swing.JButton btAdd;
        private javax.swing.JButton btBrowse;
        private javax.swing.JButton btDeselect;
        private javax.swing.JButton btHistory;
        private javax.swing.JButton btSelect;
        private javax.swing.JComboBox cbCourse;
        private javax.swing.JComboBox cbDepartment;
        private javax.swing.JComboBox cbType;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JLabel lbPath;
        private javax.swing.JTextField tfDescription;
        private javax.swing.JTextField tfTitle;
        // End of variables declaration                   
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Faculty.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Faculty.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Faculty.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faculty.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Faculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmtf;
    private javax.swing.JComboBox coursecb;
    private javax.swing.JComboBox departmentcb;
    private javax.swing.JPanel facultypan;
    private javax.swing.JTextField facultytf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel loginpan;
    private javax.swing.JTextField nametf;
    private javax.swing.JPasswordField password1tf;
    private javax.swing.JPasswordField passwordtf;
    private javax.swing.JPanel registerpan;
    // End of variables declaration//GEN-END:variables
}
