/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Faculty;

import com.oracle.jrockit.jfr.ContentType;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sahib
 */
public class Faculty extends javax.swing.JFrame {

    /**
     * Creates new form Faculty
     */
    Socket sock;
    DataInputStream dis;
    DataOutputStream dos;
    int facultyid;
    FacultyHomepage ob;
    ChangePassword ob1;
    
    public Faculty() {
        initComponents();
        setSize(400, 200);
        registerpan.setVisible(false);
        loginpan.setVisible(false);
        facultypan.setVisible(false);
        try {
            sock = new Socket("127.0.0.1", 65000);
            System.out.println("Success");
            dis = new DataInputStream(sock.getInputStream());
            dos = new DataOutputStream(sock.getOutputStream());
            String s = dis.readLine();
            if (s.equals("Hello")) {
                Thread t = new Thread(new Receiver());
                t.start();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Connection could not be established");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        facultypan = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        registerpan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordtf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        confirmtf = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        coursecb = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        departmentcb = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        loginpan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        facultytf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        password1tf = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel1.setText("FACULTY");

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("Password");

        jLabel4.setText("Confirm Password");

        jLabel5.setText("Course");

        coursecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Course" }));

        jLabel6.setText("Department");

        departmentcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Department" }));

        jButton3.setText("REGISTER");

        javax.swing.GroupLayout registerpanLayout = new javax.swing.GroupLayout(registerpan);
        registerpan.setLayout(registerpanLayout);
        registerpanLayout.setHorizontalGroup(
            registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coursecb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(departmentcb, 0, 197, Short.MAX_VALUE)
                    .addComponent(confirmtf)
                    .addComponent(nametf)
                    .addComponent(passwordtf))
                .addContainerGap())
            .addGroup(registerpanLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerpanLayout.setVerticalGroup(
            registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(confirmtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(departmentcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(coursecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel7.setText("Faculty Id");

        jLabel8.setText("Password");

        jButton4.setText("LOGIN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginpanLayout = new javax.swing.GroupLayout(loginpan);
        loginpan.setLayout(loginpanLayout);
        loginpanLayout.setHorizontalGroup(
            loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password1tf, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(facultytf))
                .addContainerGap())
            .addGroup(loginpanLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginpanLayout.setVerticalGroup(
            loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(facultytf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(password1tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout facultypanLayout = new javax.swing.GroupLayout(facultypan);
        facultypan.setLayout(facultypanLayout);
        facultypanLayout.setHorizontalGroup(
            facultypanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facultypanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultypanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerpan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, facultypanLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        facultypanLayout.setVerticalGroup(
            facultypanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultypanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultypanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(30, 30, 30)
                .addComponent(registerpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(facultypan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(facultypan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        registerpan.setVisible(true);
        loginpan.setVisible(false);
        setSize(400, 420);
        try {
            dos.writeBytes("Request Department\r\n");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Could not fetch Sufficient Data");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void departmentcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentcbActionPerformed
        try {
            if (departmentcb.getSelectedIndex() != 0) {
                dos.writeBytes("Request Course\r\n");
                dos.writeBytes(departmentcb.getSelectedItem() + "\r\n");
            } else {
                coursecb.removeAllItems();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_departmentcbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (nametf.getText().equals("") || passwordtf.getText().equals("") || confirmtf.getText().equals("") || departmentcb.getSelectedIndex() == 0 || coursecb.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "All Fields are mandatory");
        } else {
            if (passwordtf.getText().equals(confirmtf.getText())) {
                try {
                    dos.writeBytes("Register Faculty Request\r\n");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Unable to send register request");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Passwords do not match");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        loginpan.setVisible(true);
        registerpan.setVisible(false);
        setSize(400, 310);
        loginpan.setBounds(100, 10, 390, 200);
        facultytf.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (facultytf.getText().equals("") || password1tf.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Both fields are mandatory");
        } else {
            try {
                facultyid = Integer.parseInt(facultytf.getText());
                try {
                    dos.writeBytes("Faculty Login Request\r\n");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Connection with server failed");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Faculty id must be integer");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    
    class Receiver implements Runnable {
        
        @Override
        public void run() {
            facultypan.setVisible(true);
            try {
                while (true) {
                    String s = dis.readLine();
                    if (s.equals("Department March")) {
                        departmentcb.removeAllItems();
                        departmentcb.addItem("Select Department");
                        while (true) {
                            String s1 = dis.readLine();
                            if (s1.equals("khatam")) {
                                break;
                            } else {
                                departmentcb.addItem(s1);
                            }
                        }
                    } else if (s.equals("Course March")) {
                        coursecb.removeAllItems();
                        coursecb.addItem("Select Course");
                        while (true) {
                            String s1 = dis.readLine();
                            if (s1.equals("khatam")) {
                                break;
                            } else {
                                coursecb.addItem(s1);
                            }
                        }
                    } else if (s.equals("Register Faculty Request Accepted")) {
                        dos.writeBytes(nametf.getText() + "\r\n");
                        dos.writeBytes(passwordtf.getText() + "\r\n");
                        dos.writeBytes(departmentcb.getSelectedItem().toString() + "\r\n");
                        dos.writeBytes(coursecb.getSelectedItem().toString() + "\r\n");
                        Date d = new Date();
                        System.out.println(d.getTime());
                        dos.writeLong(d.getTime());
                        String s1 = dis.readLine();
                        if (s1.equals("Registered Successfully")) {
                            int id = dis.readInt();
                            JOptionPane.showMessageDialog(null, "Registered Successfully\nYou can login using ID: " + id);
                            nametf.setText("");
                            passwordtf.setText("");
                            confirmtf.setText("");
                            coursecb.setSelectedIndex(0);
                            registerpan.setVisible(false);
                            setSize(400, 200);
                        }
                    } else if (s.equals("Faculty Login Request Accepted")) {
                        dos.writeInt(facultyid);
                        dos.writeBytes(password1tf.getText() + "\r\n");
                        String s1 = dis.readLine();
                        if (s1.equals("Login Successful")) {
                            dispose();
                            ob = new Faculty.FacultyHomepage();
                            ob.setVisible(true);
                            ob.namelb.setText(dis.readLine());
                            ob.departmentlb.setText(dis.readLine());
                            ob.courselb.setText(dis.readLine());
                            String email = dis.readLine();
                            if (!email.equals("null")) {
                                ob.emaillb.setText(email);
                            } else {
                                ob.emaillb.setText("      --");
                            }
                            String contact = dis.readLine();
                            if (!contact.equals("null")) {
                                ob.contactlb.setText(contact);
                            } else {
                                ob.contactlb.setText("      --");
                            }
                            String address = dis.readLine();
                            if (!address.equals("null")) {
                                ob.addresslb.setText(address);
                            } else {
                                ob.addresslb.setText("      --");
                            }
                            String qualification = dis.readLine();
                            if (!qualification.equals("null")) {
                                ob.qualificationlb.setText(qualification);
                            } else {
                                ob.qualificationlb.setText("      --");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Invalid FacultyID or Password");
                        }
                    } else if (s.equals("Faculty Change Password Request Accepted")) {
                        try {
                            dos.writeInt(facultyid);
                            dos.writeBytes(ob1.currentpasstf.getText() + "\r\n");
                            dos.writeBytes(ob1.newpasstf.getText() + "\r\n");
                            String s2 = dis.readLine();
                            System.out.println(s2);
                            if(s2.equals("Password Change Successful")) {
                                JOptionPane.showMessageDialog(null, "Password Change Successful");
                                ob1.dispose();
                            } else if(s2.equals("Invalid Current Password")){
                                JOptionPane.showMessageDialog(null, "Invalid Current Password");
                            }
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
    public class FacultyHomepage extends javax.swing.JFrame {

        /**
         * Creates new form FacultyHomepage
         */
        public FacultyHomepage() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {
            
            jLabel1 = new javax.swing.JLabel();
            jPanel1 = new javax.swing.JPanel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();
            qualificationlb = new javax.swing.JLabel();
            addresslb = new javax.swing.JLabel();
            contactlb = new javax.swing.JLabel();
            emaillb = new javax.swing.JLabel();
            courselb = new javax.swing.JLabel();
            departmentlb = new javax.swing.JLabel();
            namelb = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();
            jButton3 = new javax.swing.JButton();
            jButton4 = new javax.swing.JButton();
            jButton5 = new javax.swing.JButton();
            jButton6 = new javax.swing.JButton();
            
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            
            jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
            jLabel1.setText("FACULTY HOMEPAGE");
            
            jLabel2.setText("Photo Here");
            
            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addContainerGap(75, Short.MAX_VALUE))
            );
            
            jLabel3.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel3.setText("Name");
            
            jLabel4.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel4.setText("Department");
            
            jLabel5.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel5.setText("Course");
            
            jLabel6.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel6.setText("Email");
            
            jLabel7.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel7.setText("Contact");
            
            jLabel8.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel8.setText("Address");
            
            jLabel9.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel9.setText("Qualification");
            
            qualificationlb.setText("jLabel10");
            
            addresslb.setText("jLabel11");
            
            contactlb.setText("jLabel12");
            
            emaillb.setText("jLabel13");
            
            courselb.setText("jLabel14");
            
            departmentlb.setText("jLabel15");
            
            namelb.setText("jLabel16");
            
            jButton1.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton1.setText("Change Password");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            
            jButton2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton2.setText("Edit Profile");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });
            
            jButton3.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton3.setText("Edit Profile Pic");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });
            
            jButton4.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton4.setText("View History");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });
            
            jButton5.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton5.setText("Add Notes");
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
                }
            });
            
            jButton6.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton6.setText("Sign Out");
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
                }
            });
            
            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel3))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(namelb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                                                            .addComponent(jButton1))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(departmentlb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(courselb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(emaillb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(contactlb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(qualificationlb)
                                                            .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(addresslb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(158, 158, 158)
                                            .addComponent(jLabel1)))
                            .addContainerGap())
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel3)
                                                    .addComponent(namelb)
                                                    .addComponent(jButton1))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel4)
                                                    .addComponent(departmentlb)
                                                    .addComponent(jButton2))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel5)
                                                    .addComponent(courselb)
                                                    .addComponent(jButton3))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel6)
                                                    .addComponent(emaillb)
                                                    .addComponent(jButton4))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(contactlb)
                                    .addComponent(jButton5))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(addresslb)
                                    .addComponent(jButton6))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(qualificationlb))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            
            pack();
        }// </editor-fold>                        

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            ob1 = new Faculty.ChangePassword();
            ob1.setVisible(true);
        }
        
        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }
        
        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }
        
        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }
        
        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }
        
        private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }

        /**
         * @param args the command line arguments
         */
        // Variables declaration - do not modify                     
        private javax.swing.JLabel addresslb;
        private javax.swing.JLabel contactlb;
        private javax.swing.JLabel courselb;
        private javax.swing.JLabel departmentlb;
        private javax.swing.JLabel emaillb;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JButton jButton6;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel namelb;
        private javax.swing.JLabel qualificationlb;
        // End of variables declaration                   
    }
    
    public class ChangePassword extends javax.swing.JFrame {

        /**
         * Creates new form ChangePassword
         */
        public ChangePassword() {
            initComponents();
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {
            
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            currentpasstf = new javax.swing.JPasswordField();
            jLabel3 = new javax.swing.JLabel();
            newpasstf = new javax.swing.JPasswordField();
            jLabel4 = new javax.swing.JLabel();
            confirmpasstf = new javax.swing.JPasswordField();
            jButton1 = new javax.swing.JButton();
            
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            
            jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
            jLabel1.setText("CHANGE PASSWORD");
            
            jLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jLabel2.setText("Current Password");
            
            jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jLabel3.setText("New Password");
            
            jLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jLabel4.setText("Confirm Password");
            
            jButton1.setFont(new java.awt.Font("Tekton Pro", 0, 16)); // NOI18N
            jButton1.setText("OK");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            
            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(newpasstf, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(currentpasstf, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(confirmpasstf, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel2)
                                            .addGap(0, 0, Short.MAX_VALUE)))
                            .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 58, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                            .addGap(124, 124, 124)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(currentpasstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(newpasstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(confirmpasstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                            .addComponent(jButton1)
                            .addContainerGap())
            );
            
            pack();
        }// </editor-fold>                        

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            if (currentpasstf.getText().equals("") || newpasstf.getText().equals("") || confirmpasstf.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "All Fields are Mandatory");
            } else {
                if (newpasstf.getText().equals(confirmpasstf.getText())) {
                    if (currentpasstf.getText().equals(newpasstf.getText())) {
                        JOptionPane.showMessageDialog(this, "New Password must be different from current password");
                    } else {
                        try {
                            dos.writeBytes("Faculty Change Password Request\r\n");
                        } catch (IOException ex) {
                            JOptionPane.showMessageDialog(this, "Connection Lost");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Confirm password does not match");
                }
            }
        }

        /**
         * @param args the command line arguments
         */
        // Variables declaration - do not modify                     
        private javax.swing.JPasswordField confirmpasstf;
        private javax.swing.JPasswordField currentpasstf;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPasswordField newpasstf;
        // End of variables declaration                   
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Faculty.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Faculty.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Faculty.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faculty.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Faculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmtf;
    private javax.swing.JComboBox coursecb;
    private javax.swing.JComboBox departmentcb;
    private javax.swing.JPanel facultypan;
    private javax.swing.JTextField facultytf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel loginpan;
    private javax.swing.JTextField nametf;
    private javax.swing.JPasswordField password1tf;
    private javax.swing.JPasswordField passwordtf;
    private javax.swing.JPanel registerpan;
    // End of variables declaration//GEN-END:variables
}
