/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;

import Faculty.Faculty;
import Faculty.FacultyClass;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Sahib
 */
public class Student extends javax.swing.JFrame {

    Socket sock;
    DataInputStream dis;
    DataOutputStream dos;

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        setSize(400, 200);
        registerpan.setVisible(false);
        loginpan.setVisible(false);

        try {
            sock = new Socket("127.0.0.1", 65000);
            System.out.println("Success");
            dis = new DataInputStream(sock.getInputStream());
            dos = new DataOutputStream(sock.getOutputStream());
            String s = dis.readLine();
            if (s.equals("Hello")) {
                Thread t = new Thread(new Receiver());
                t.start();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Connection could not be established");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        registerpan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordtf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        confirmpasstf = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        departmentcb = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        coursecb = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rollnotf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        loginpan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rollno1tf = new javax.swing.JTextField();
        password1tf = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT");

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel4.setText("Confirm Password");

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel5.setText("Department");

        departmentcb.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        departmentcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentcbActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel6.setText("Course");

        coursecb.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N

        jButton3.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jButton3.setText("Register");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel9.setText("Roll No");

        rollnotf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollnotfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerpanLayout = new javax.swing.GroupLayout(registerpan);
        registerpan.setLayout(registerpanLayout);
        registerpanLayout.setHorizontalGroup(
            registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerpanLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerpanLayout.createSequentialGroup()
                        .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rollnotf)
                            .addComponent(confirmpasstf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordtf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nametf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(departmentcb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(coursecb, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        registerpanLayout.setVerticalGroup(
            registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rollnotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(confirmpasstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(departmentcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(coursecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jButton2.setText("LogIn");

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel7.setText("Roll No");

        jLabel8.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel8.setText("Password");

        jButton4.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jButton4.setText("LogIn");

        javax.swing.GroupLayout loginpanLayout = new javax.swing.GroupLayout(loginpan);
        loginpan.setLayout(loginpanLayout);
        loginpanLayout.setHorizontalGroup(
            loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rollno1tf, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(password1tf))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        loginpanLayout.setVerticalGroup(
            loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rollno1tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(password1tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(registerpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollnotfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollnotfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollnotfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        registerpan.setVisible(true);
        loginpan.setVisible(false);
        setSize(400, 480);
        try {
            dos.writeBytes("Request Department\r\n");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Could not fetch Sufficient Data");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void departmentcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentcbActionPerformed
        try {
            if (departmentcb.getSelectedIndex() != 0) {
                dos.writeBytes("Request Course\r\n");
                dos.writeBytes(departmentcb.getSelectedItem() + "\r\n");
            } else {
                coursecb.removeAllItems();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_departmentcbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String rollno = rollnotf.getText();
        if (rollno.equals("") || nametf.getText().equals("") || passwordtf.getText().equals("") || confirmpasstf.getText().equals("") || departmentcb.getSelectedIndex() == 0 || coursecb.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "All Fields are mandatory");
        } else {
            boolean flag = true;
            if (rollno.length() == 11) {
                try {
                    Date d = new Date();
                    int yr = d.getYear() + 1900;
                    System.out.println(yr);
                    int year = Integer.parseInt(rollno.substring(0, 4));
                    int no = Integer.parseInt(rollno.substring(7));
                    if (year >= yr - 7 && year <= yr && no > 1000) {
                        if (passwordtf.getText().equals(confirmpasstf.getText())) {
                            try {
                                dos.writeBytes("Register Student Request\r\n");
                            } catch (IOException ex) {
                                JOptionPane.showMessageDialog(this, "Unable to send register request");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Passwords do not match");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Roll No not in proper format1");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Roll No not in proper format2");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Roll No not in proper format3");
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    class Receiver implements Runnable {

        @Override
        public void run() {
            try {
                while (true) {
                    String s = dis.readLine();
                    if (s.equals("Department March")) {
                        departmentcb.removeAllItems();
                        departmentcb.addItem("Select Department");
                        while (true) {
                            String s1 = dis.readLine();
                            if (s1.equals("khatam")) {
                                break;
                            } else {
                                departmentcb.addItem(s1);
                            }
                        }
                    } else if (s.equals("Course March")) {
                        coursecb.removeAllItems();
                        coursecb.addItem("Select Course");
                        while (true) {
                            String s1 = dis.readLine();
                            if (s1.equals("khatam")) {
                                break;
                            } else {
                                coursecb.addItem(s1);
                            }
                        }
                    } else if (s.equals("Register Student Request Accepted")) {
                        System.out.println("2");
                        dos.writeBytes(rollnotf.getText() + "\r\n");
                        dos.writeBytes(nametf.getText() + "\r\n");
                        dos.writeBytes(passwordtf.getText() + "\r\n");
                        dos.writeBytes(departmentcb.getSelectedItem().toString() + "\r\n");
                        dos.writeBytes(coursecb.getSelectedItem().toString() + "\r\n");
                        String s1 = dis.readLine();
                        if (s1.equals("Registered Successfully")) {
                            JOptionPane.showMessageDialog(null, s1);
                            nametf.setText("");
                            passwordtf.setText("");
                            confirmpasstf.setText("");
                            coursecb.setSelectedIndex(0);
                            registerpan.setVisible(false);
                            setSize(400, 200);
                        }
                    }/* else if (s.equals("Faculty Login Request Accepted")) {
                        dos.writeInt(fac.id);
                        dos.writeBytes(password1tf.getText() + "\r\n");
                        String s1 = dis.readLine();
                        if (s1.equals("Login Successful")) {
                            dispose();
                            dos.writeBytes("Faculty Data Request\r\n");
                        } else {
                            JOptionPane.showMessageDialog(ob, "Invalid FacultyID or Password");
                        }
                    } else if (s.equals("Faculty Data Request Accepted")) {
                        dos.writeInt(fac.id);
                        System.out.println(fac.id);
                        fac.username = dis.readLine();
                        fac.department = dis.readLine();
                        fac.course = dis.readLine();
                        fac.email = dis.readLine();
                        fac.contact = dis.readLine();
                        fac.address = dis.readLine();
                        fac.qualification = dis.readLine();
                        ob = new Faculty.FacultyHomepage();
                        ob.setVisible(true);
                    } else if (s.equals("Faculty Change Password Request Accepted")) {
                        try {
                            dos.writeInt(fac.id);
                            dos.writeBytes(ob1.currentpasstf.getText() + "\r\n");
                            dos.writeBytes(ob1.newpasstf.getText() + "\r\n");
                            String s2 = dis.readLine();
                            if (s2.equals("Password Change Successful")) {
                                JOptionPane.showMessageDialog(ob1, "Password Change Successful");
                                ob1.dispose();
                            } else if (s2.equals("Invalid Current Password")) {
                                JOptionPane.showMessageDialog(ob1, "Invalid Current Password");
                            }
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    } else if (s.equals("Faculty Edit Profile Request Accepted")) {
                        try {
                            dos.writeInt(fac.id);
                            dos.writeBytes(ob2.emailtf.getText() + "\r\n");
                            dos.writeBytes(ob2.contacttf.getText() + "\r\n");
                            dos.writeBytes(ob2.addressta.getText() + "\r\n");
                            dos.writeBytes(ob2.qualificationta.getText() + "\r\n");
                            String s1 = dis.readLine();
                            if (s1.equals("Profile Updated Successfully")) {
                                JOptionPane.showMessageDialog(ob2, s1);
                                ob2.dispose();
                                ob.dispose();
                                dos.writeBytes("Faculty Data Request\r\n");
                            } else {
                                JOptionPane.showMessageDialog(ob2, "Profile Update Failed");;
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Connection Lost");
                        }
                    }*/
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmpasstf;
    private javax.swing.JComboBox coursecb;
    private javax.swing.JComboBox departmentcb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel loginpan;
    private javax.swing.JTextField nametf;
    private javax.swing.JPasswordField password1tf;
    private javax.swing.JPasswordField passwordtf;
    private javax.swing.JPanel registerpan;
    private javax.swing.JTextField rollno1tf;
    private javax.swing.JTextField rollnotf;
    // End of variables declaration//GEN-END:variables
}
