/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Sahib
 */
public class Student extends javax.swing.JFrame {

    Socket sock;
    DataInputStream dis;
    DataOutputStream dos;
    StudentClass stu;
    StudentHomepage ob;
    ChangePassword ob1;
    EditProfile ob2;

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        setSize(400, 200);
        registerpan.setVisible(false);
        loginpan.setVisible(false);
        stu = new StudentClass();
        try {
            sock = new Socket("127.0.0.1", 65000);
            System.out.println("Success");
            dis = new DataInputStream(sock.getInputStream());
            dos = new DataOutputStream(sock.getOutputStream());
            String s = dis.readLine();
            if (s.equals("Hello")) {
                Thread t = new Thread(new Receiver());
                t.start();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Connection could not be established");
            System.exit(0);
        }
    }

    boolean checkRollNo(String rollno) {
        if (rollno.length() == 11) {
            try {
                Date d = new Date();
                int yr = d.getYear() + 1900;
                int year = Integer.parseInt(rollno.substring(0, 4));
                int no = Integer.parseInt(rollno.substring(7));
                if (year >= yr - 7 && year <= yr && no > 1000) {
                    return true;
                } else {
                    return false;
                }
            } catch (Exception e) {
                return false;
            }
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        registerpan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordtf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        confirmpasstf = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        departmentcb = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        coursecb = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rollnotf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        loginpan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rollno1tf = new javax.swing.JTextField();
        password1tf = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT");

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel4.setText("Confirm Password");

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel5.setText("Department");

        departmentcb.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        departmentcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentcbActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel6.setText("Course");

        coursecb.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N

        jButton3.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jButton3.setText("Register");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel9.setText("Roll No");

        rollnotf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollnotfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerpanLayout = new javax.swing.GroupLayout(registerpan);
        registerpan.setLayout(registerpanLayout);
        registerpanLayout.setHorizontalGroup(
            registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerpanLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerpanLayout.createSequentialGroup()
                        .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rollnotf)
                            .addComponent(confirmpasstf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordtf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nametf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(departmentcb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(coursecb, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        registerpanLayout.setVerticalGroup(
            registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rollnotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(confirmpasstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(departmentcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(coursecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jButton2.setText("LogIn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel7.setText("Roll No");

        jLabel8.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel8.setText("Password");

        jButton4.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jButton4.setText("LogIn");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginpanLayout = new javax.swing.GroupLayout(loginpan);
        loginpan.setLayout(loginpanLayout);
        loginpanLayout.setHorizontalGroup(
            loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rollno1tf, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(password1tf))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        loginpanLayout.setVerticalGroup(
            loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rollno1tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(password1tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(registerpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollnotfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollnotfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollnotfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        registerpan.setVisible(true);
        loginpan.setVisible(false);
        rollnotf.requestFocus();
        setSize(400, 480);
        try {
            dos.writeBytes("Request Department\r\n");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Could not fetch Sufficient Data");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void departmentcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentcbActionPerformed
        try {
            if (departmentcb.getSelectedIndex() != 0) {
                dos.writeBytes("Request Course\r\n");
                dos.writeBytes(departmentcb.getSelectedItem() + "\r\n");
            } else {
                coursecb.removeAllItems();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_departmentcbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String rollno = rollnotf.getText();
        if (rollno.equals("") || nametf.getText().equals("") || passwordtf.getText().equals("") || confirmpasstf.getText().equals("") || departmentcb.getSelectedIndex() == 0 || coursecb.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "All Fields are mandatory");
        } else {
            if (checkRollNo(rollno)) {
                if (passwordtf.getText().equals(confirmpasstf.getText())) {
                    try {
                        dos.writeBytes("Register Student Request\r\n");
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, "Unable to send register request");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Passwords do not match");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Roll No not in proper format");
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        loginpan.setVisible(true);
        registerpan.setVisible(false);
        setSize(400, 310);
        loginpan.setBounds(100, 10, 390, 200);
        rollno1tf.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        stu.rollno = rollno1tf.getText();
        if (stu.rollno.equals("") || password1tf.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Both fields are mandatory");
        } else {
            if (checkRollNo(stu.rollno)) {
                try {
                    dos.writeBytes("Student Login Request\r\n");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Connection with server failed");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Roll No not in proper format");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    class Receiver implements Runnable {

        @Override
        public void run() {
            try {
                while (true) {
                    String s = dis.readLine();
                    if (s.equals("Department March")) {
                        departmentcb.removeAllItems();
                        departmentcb.addItem("Select Department");
                        while (true) {
                            String s1 = dis.readLine();
                            if (s1.equals("khatam")) {
                                break;
                            } else {
                                departmentcb.addItem(s1);
                            }
                        }
                    } else if (s.equals("Course March")) {
                        coursecb.removeAllItems();
                        coursecb.addItem("Select Course");
                        while (true) {
                            String s1 = dis.readLine();
                            if (s1.equals("khatam")) {
                                break;
                            } else {
                                coursecb.addItem(s1);
                            }
                        }
                    } else if (s.equals("Register Student Request Accepted")) {

                        dos.writeBytes(rollnotf.getText() + "\r\n");
                        dos.writeBytes(nametf.getText() + "\r\n");
                        dos.writeBytes(passwordtf.getText() + "\r\n");
                        dos.writeBytes(departmentcb.getSelectedItem().toString() + "\r\n");
                        dos.writeBytes(coursecb.getSelectedItem().toString() + "\r\n");

                        String s1 = dis.readLine();

                        if (s1.equals("Registered Successfully")) {

                            JOptionPane.showMessageDialog(null, s1);
                            nametf.setText("");
                            passwordtf.setText("");
                            confirmpasstf.setText("");
                            coursecb.setSelectedIndex(0);
                            registerpan.setVisible(false);
                            setSize(400, 200);
                        } else {
                            JOptionPane.showMessageDialog(null, s1);
                        }
                    } else if (s.equals("Student Login Request Accepted")) {
                        dos.writeBytes(stu.rollno + "\r\n");
                        dos.writeBytes(password1tf.getText() + "\r\n");
                        String s1 = dis.readLine();
                        if (s1.equals("Login Successful")) {
                            dispose();
                            dos.writeBytes("Student Data Request\r\n");
                        } else {
                            JOptionPane.showMessageDialog(null, "Invalid Roll No or Password");
                        }
                    } else if (s.equals("Student Data Request Accepted")) {
                        dos.writeBytes(stu.rollno + "\r\n");
                        stu.name = dis.readLine();
                        stu.department = dis.readLine();
                        stu.course = dis.readLine();
                        stu.email = dis.readLine();
                        stu.contact = dis.readLine();
                        stu.address = dis.readLine();
                        ob = new Student.StudentHomepage();
                        ob.setVisible(true);
                    } else if (s.equals("Student Change Password Request Accepted")) {
                        try {
                            dos.writeBytes(stu.rollno + "\r\n");
                            dos.writeBytes(ob1.currentpasstf.getText() + "\r\n");
                            dos.writeBytes(ob1.newpasstf.getText() + "\r\n");
                            String s2 = dis.readLine();
                            if (s2.equals("Password Change Successful")) {
                                JOptionPane.showMessageDialog(ob1, "Password Change Successful");
                                ob1.dispose();
                            } else if (s2.equals("Invalid Current Password")) {
                                JOptionPane.showMessageDialog(ob1, "Invalid Current Password");
                            }
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    } else if (s.equals("Student Edit Profile Request Accepted")) {
                        try {
                            dos.writeBytes(stu.rollno + "\r\n");
                            dos.writeBytes(ob2.emailtf.getText() + "\r\n");
                            dos.writeBytes(ob2.contacttf.getText() + "\r\n");
                            dos.writeBytes(ob2.addressta.getText() + "\r\n");
                            String s1 = dis.readLine();
                            if (s1.equals("Profile Updated Successfully")) {
                                JOptionPane.showMessageDialog(ob2, s1);
                                ob2.dispose();
                                ob.dispose();
                                dos.writeBytes("Student Data Request\r\n");
                            } else {
                                JOptionPane.showMessageDialog(ob2, "Profile Update Failed");;
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Connection Lost");
                        }
                    }

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public class StudentHomepage extends javax.swing.JFrame {

        /**
         * Creates new form StudentHomepage
         */
        public StudentHomepage() {
            initComponents();
            setSize(600,460);
            rollnolb.setText(stu.rollno);
            namelb.setText(stu.name);
            departmentlb.setText(stu.department);
            courselb.setText(stu.course);
            if (!stu.email.equals("null")) {
                emaillb.setText(stu.email);
            } else {
                emaillb.setText("      --");
            }
            if (!stu.contact.equals("null")) {
                contactlb.setText(stu.contact);
            } else {
                contactlb.setText("      --");
            }
            if (!stu.address.equals("null")) {
                addresslb.setText(stu.address);
            } else {
                addresslb.setText("      --");
            }
            setVisible(true);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            photopan = new javax.swing.JPanel();
            photolb = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();
            departmentlb = new javax.swing.JLabel();
            namelb = new javax.swing.JLabel();
            rollnolb = new javax.swing.JLabel();
            courselb = new javax.swing.JLabel();
            emaillb = new javax.swing.JLabel();
            contactlb = new javax.swing.JLabel();
            addresslb = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();
            jButton3 = new javax.swing.JButton();
            jButton4 = new javax.swing.JButton();
            jButton5 = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
            jLabel1.setText("STUDENT HOMEPAGE");

            photolb.setText("Photo Here");

            javax.swing.GroupLayout photopanLayout = new javax.swing.GroupLayout(photopan);
            photopan.setLayout(photopanLayout);
            photopanLayout.setHorizontalGroup(
                    photopanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(photopanLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(photolb)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            photopanLayout.setVerticalGroup(
                    photopanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(photopanLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(photolb)
                            .addContainerGap(75, Short.MAX_VALUE))
            );

            jLabel3.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel3.setText("Roll No");

            jLabel4.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel4.setText("Name");

            jLabel5.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel5.setText("Department");

            jLabel6.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel6.setText("Course");

            jLabel7.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel7.setText("Email");

            jLabel8.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel8.setText("Contact");

            jLabel9.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel9.setText("Address");

            departmentlb.setText("jLabel10");

            namelb.setText("jLabel10");

            rollnolb.setText("jLabel10");

            courselb.setText("jLabel10");

            emaillb.setText("jLabel10");

            contactlb.setText("jLabel10");

            addresslb.setText("jLabel10");

            jButton1.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton1.setText("Change Password");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton2.setText("Edit Profile");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jButton3.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton3.setText("Change Photo");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });

            jButton4.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton4.setText("Download Notes");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });

            jButton5.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jButton5.setText("Sign Out");
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(photopan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel9))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(rollnolb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                                                            .addComponent(jButton1))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(namelb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(departmentlb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(courselb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(addresslb)
                                                                    .addComponent(contactlb))
                                                            .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(emaillb)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(112, 112, 112)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap())
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(photopan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel3)
                                                    .addComponent(rollnolb)
                                                    .addComponent(jButton1))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel4)
                                                    .addComponent(namelb)
                                                    .addComponent(jButton2))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel5)
                                                    .addComponent(departmentlb)
                                                    .addComponent(jButton3))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel6)
                                                    .addComponent(courselb)
                                                    .addComponent(jButton4))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(emaillb)
                                    .addComponent(jButton5))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(contactlb))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(addresslb))
                            .addGap(21, 21, 21))
            );

            pack();
        }// </editor-fold>                        

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            ob1 = new Student.ChangePassword();
            ob1.setVisible(true);
        }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
            ob2 = new Student.EditProfile();
            ob2.setVisible(true);

        }

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }

        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
            System.exit(0);
        }

        /**
         * @param args the command line arguments
         */
        // Variables declaration - do not modify                     
        private javax.swing.JLabel addresslb;
        private javax.swing.JLabel contactlb;
        private javax.swing.JLabel courselb;
        private javax.swing.JLabel departmentlb;
        private javax.swing.JLabel emaillb;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JLabel namelb;
        private javax.swing.JLabel photolb;
        private javax.swing.JPanel photopan;
        private javax.swing.JLabel rollnolb;
        // End of variables declaration                   
    }

    public class ChangePassword extends javax.swing.JFrame {

        /**
         * Creates new form ChangePassword
         */
        public ChangePassword() {
            initComponents();
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            confirmpasstf = new javax.swing.JPasswordField();
            jButton1 = new javax.swing.JButton();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            currentpasstf = new javax.swing.JPasswordField();
            jLabel3 = new javax.swing.JLabel();
            newpasstf = new javax.swing.JPasswordField();
            jLabel4 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jButton1.setFont(new java.awt.Font("Tekton Pro", 0, 16)); // NOI18N
            jButton1.setText("OK");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
            jLabel1.setText("CHANGE PASSWORD");

            jLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jLabel2.setText("Current Password");

            jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jLabel3.setText("New Password");

            jLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
            jLabel4.setText("Confirm Password");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(newpasstf, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(currentpasstf, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(confirmpasstf, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(0, 0, Short.MAX_VALUE)))
                            .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 114, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(currentpasstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(newpasstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(confirmpasstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                            .addComponent(jButton1)
                            .addContainerGap())
            );

            pack();
        }// </editor-fold>                        

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            if (currentpasstf.getText().equals("") || newpasstf.getText().equals("") || confirmpasstf.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "All Fields are Mandatory");
            } else {
                if (newpasstf.getText().equals(confirmpasstf.getText())) {
                    if (currentpasstf.getText().equals(newpasstf.getText())) {
                        JOptionPane.showMessageDialog(this, "New Password must be different from current password");
                    } else {
                        try {
                            dos.writeBytes("Student Change Password Request\r\n");
                        } catch (IOException ex) {
                            JOptionPane.showMessageDialog(this, "Connection Lost");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Confirm password does not match");
                }
            }
        }

        /**
         * @param args the command line arguments
         */
        // Variables declaration - do not modify                     
        private javax.swing.JPasswordField confirmpasstf;
        private javax.swing.JPasswordField currentpasstf;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPasswordField newpasstf;
        // End of variables declaration                   
    }

    public class EditProfile extends javax.swing.JFrame {

        /**
         * Creates new form EditProfile
         */
        public EditProfile() {
            initComponents();
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            namelb.setText(stu.name);
            if (!stu.email.equals("null")) {
                emailtf.setText(stu.email);
            }
            if (!stu.contact.equals("null")) {
                contacttf.setText(stu.contact);
            }
            if (!stu.address.equals("null")) {
                addressta.setText(stu.address);
            }
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            emailtf = new javax.swing.JTextField();
            contacttf = new javax.swing.JTextField();
            jScrollPane1 = new javax.swing.JScrollPane();
            addressta = new javax.swing.JTextArea();
            jLabel1 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            jLabel2 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            namelb = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel3.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel3.setText("Contact");

            jLabel4.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel4.setText("Address");

            addressta.setColumns(20);
            addressta.setRows(5);
            jScrollPane1.setViewportView(addressta);

            jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
            jLabel1.setText("EDIT PROFILE");

            jButton1.setText("Update");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jLabel2.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
            jLabel2.setText("Email");

            jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            jLabel5.setText("Name");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(97, 97, 97)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 74, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel3)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(contacttf, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel4)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(jLabel5))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(emailtf, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                                                    .addComponent(namelb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(namelb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2))
                                            .addGap(18, 18, 18)
                                            .addComponent(contacttf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addComponent(jButton1)
                            .addContainerGap(47, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>                        

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            String email = emailtf.getText();
            String contact = contacttf.getText();
            String address = addressta.getText();
            if (email.equals(stu.email) && contact.equals(stu.contact) && address.equals(stu.address)) {
                JOptionPane.showMessageDialog(this, "You must change atleast one field");
            } else {
                boolean flag = true, flag2 = true;
                if (contact.length() >= 10 && contact.length() <= 12) {
                    try {
                        Long.parseLong(contact);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Contact can contain only digits");
                        flag = false;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Contact can only contain 10-12 digits");
                    flag = false;
                }
                if (email.contains("@")) {
                    email = email.substring(email.indexOf('@'));
                    if (email.contains(".")) {
                    } else {
                        flag2 = false;
                        JOptionPane.showMessageDialog(this, "Email address not valid");
                    }
                } else {
                    flag2 = false;
                    JOptionPane.showMessageDialog(this, "@ must be included in email");
                    emailtf.requestFocus();
                }
                if (flag && flag2) {
                    try {
                        dos.writeBytes("Student Edit Profile Request\r\n");
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, "Connection Lost");
                    }
                }
            }

        }

        /**
         * @param args the command line arguments
         */
        // Variables declaration - do not modify                     
        private javax.swing.JTextArea addressta;
        private javax.swing.JTextField contacttf;
        private javax.swing.JTextField emailtf;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel namelb;
    // End of variables declaration                   
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmpasstf;
    private javax.swing.JComboBox coursecb;
    private javax.swing.JComboBox departmentcb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel loginpan;
    private javax.swing.JTextField nametf;
    private javax.swing.JPasswordField password1tf;
    private javax.swing.JPasswordField passwordtf;
    private javax.swing.JPanel registerpan;
    private javax.swing.JTextField rollno1tf;
    private javax.swing.JTextField rollnotf;
    // End of variables declaration//GEN-END:variables
}
